# Generated by Django 4.0 on 2021-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_rename_employee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(default='STU', max_length=3),
        ),
    ]
