# Generated by Django 4.0 on 2021-12-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0003_student_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_code',
        ),
    ]
